
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 11 18:46:54 CST 2018
//----------------------------------------------------

package Lexic;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CORCHETES = 26;
  public static final int PAR_DER = 23;
  public static final int READLINE = 49;
  public static final int ASIGNAR = 11;
  public static final int MULT = 4;
  public static final int DIFERENTE = 13;
  public static final int INTEGER = 53;
  public static final int RESTA = 3;
  public static final int DOUBLE = 29;
  public static final int INTERFACE = 34;
  public static final int INT = 28;
  public static final int COR_DER = 21;
  public static final int FOR = 39;
  public static final int LLAVE_IZQ = 24;
  public static final int NOT = 16;
  public static final int AND = 14;
  public static final int READINTEGER = 48;
  public static final int IGUAL = 12;
  public static final int OR = 15;
  public static final int BOOL = 31;
  public static final int DOUBLECONSTANT = 58;
  public static final int CLASS = 33;
  public static final int DIV = 5;
  public static final int NEWARRAY = 46;
  public static final int SUMA = 2;
  public static final int BOOLCONSTANT = 59;
  public static final int IF = 41;
  public static final int GETBYTE = 55;
  public static final int THIS = 36;
  public static final int INTCONSTANT = 57;
  public static final int SETBYTE = 56;
  public static final int EOF = 0;
  public static final int RETURN = 43;
  public static final int TRUE = 51;
  public static final int STRINGCONSTANT = 60;
  public static final int NEW = 45;
  public static final int error = 1;
  public static final int COMA = 18;
  public static final int SEMI_COLON = 17;
  public static final int NULL = 35;
  public static final int MENOR = 7;
  public static final int MOD = 6;
  public static final int IDENT = 54;
  public static final int BREAK = 44;
  public static final int PAR_IZQ = 22;
  public static final int VOID = 27;
  public static final int MAYOR = 9;
  public static final int ELSE = 42;
  public static final int LLAVE_DER = 25;
  public static final int PUNTO = 19;
  public static final int WHILE = 40;
  public static final int MAYOR_IGUAL = 10;
  public static final int COR_IZQ = 20;
  public static final int EXTENDS = 37;
  public static final int HEXADECIMAL = 30;
  public static final int STRING = 32;
  public static final int MALLOC = 50;
  public static final int MENOR_IGUAL = 8;
  public static final int FALSE = 52;
  public static final int IMPLEMENTS = 38;
  public static final int PRINT = 47;
}

