/* The following code was generated by JFlex 1.6.1 */

package Lexic;
import java.io.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/cachi/Documents/Landivar/Compiladores/Compiladores-AnalizadorLexico/MiniC#/src/Lexic/Yylex.flex</tt>
 */
public class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\71\1\70\1\71\1\71\1\3\22\0\1\67\1\47\1\63"+
    "\2\0\1\46\1\51\1\0\1\55\1\56\1\2\1\45\1\46\1\45"+
    "\1\52\1\1\1\64\11\61\1\0\1\46\1\47\1\50\1\47\2\0"+
    "\1\34\3\66\1\41\1\42\5\62\1\43\1\62\1\33\3\62\1\37"+
    "\1\44\1\36\1\40\2\62\1\65\2\62\1\53\1\0\1\54\1\0"+
    "\1\62\1\0\1\23\1\14\1\22\1\10\1\16\1\24\1\21\1\25"+
    "\1\7\1\62\1\32\1\15\1\27\1\11\1\6\1\30\1\62\1\20"+
    "\1\17\1\12\1\13\1\5\1\31\1\26\1\35\1\62\1\57\1\4"+
    "\1\60\7\0\1\71\32\0\1\71\u15df\0\1\71\u097f\0\13\71\35\0"+
    "\1\71\1\71\5\0\1\71\57\0\1\71\u0fa0\0\1\71\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ud00f\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\1\20\4\2\2\1\1"+
    "\3\2\1\5\1\1\1\5\1\6\1\7\1\0\2\4"+
    "\1\10\22\4\1\0\1\11\2\0\1\7\1\12\1\0"+
    "\1\4\1\10\15\4\1\10\2\4\1\0\1\13\1\14"+
    "\1\0\1\15\2\4\1\16\5\4\1\0\1\11\1\0"+
    "\15\4";

  private static int [] zzUnpackAction() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\164\0\72\0\256\0\350\0\u0122\0\u015c"+
    "\0\u0196\0\u01d0\0\u020a\0\u0244\0\u027e\0\u02b8\0\u02f2\0\u032c"+
    "\0\u0366\0\u03a0\0\u03da\0\u0414\0\u044e\0\u0488\0\u04c2\0\u04fc"+
    "\0\u0536\0\u0570\0\u05aa\0\u05e4\0\u061e\0\u0658\0\u0692\0\256"+
    "\0\u06cc\0\u0706\0\u0740\0\u077a\0\u015c\0\u07b4\0\u07ee\0\u0828"+
    "\0\u0862\0\u089c\0\u08d6\0\u0910\0\u094a\0\u0984\0\u09be\0\u09f8"+
    "\0\u0a32\0\u0a6c\0\u0aa6\0\u0ae0\0\u0b1a\0\u0b54\0\u0b8e\0\u0bc8"+
    "\0\u0c02\0\u0c3c\0\u0c76\0\72\0\u0cb0\0\u0cea\0\u0d24\0\u0d5e"+
    "\0\u0d98\0\u0dd2\0\u0e0c\0\u0e46\0\u0e80\0\u0eba\0\u0ef4\0\u0f2e"+
    "\0\u0f68\0\u0fa2\0\u0fdc\0\u1016\0\u1050\0\u108a\0\u10c4\0\u10fe"+
    "\0\u1138\0\u0c3c\0\u0c76\0\u1172\0\72\0\u11ac\0\u11e6\0\u015c"+
    "\0\u1220\0\u125a\0\u1294\0\u12ce\0\u1308\0\u1342\0\u1342\0\u137c"+
    "\0\u13b6\0\u13f0\0\u142a\0\u1464\0\u149e\0\u14d8\0\u1512\0\u154c"+
    "\0\u1586\0\u15c0\0\u15fa\0\u1634\0\u166e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\10\1\15\1\10\1\16\1\17"+
    "\1\20\1\10\1\21\1\10\1\22\4\10\1\23\1\10"+
    "\1\24\2\10\1\25\3\10\1\26\2\10\1\27\1\4"+
    "\2\30\1\31\1\4\1\32\1\4\1\33\1\4\1\34"+
    "\1\4\1\35\1\10\1\36\1\37\2\10\2\40\1\5"+
    "\73\0\1\41\1\42\72\0\1\5\63\0\3\5\4\0"+
    "\1\4\72\0\1\10\1\43\36\10\14\0\2\10\1\0"+
    "\3\10\10\0\40\10\14\0\2\10\1\0\3\10\10\0"+
    "\4\10\1\44\12\10\1\45\2\10\1\46\15\10\14\0"+
    "\2\10\1\0\3\10\10\0\1\10\1\47\36\10\14\0"+
    "\2\10\1\0\3\10\10\0\6\10\1\50\31\10\14\0"+
    "\2\10\1\0\3\10\10\0\13\10\1\51\4\10\1\52"+
    "\17\10\14\0\2\10\1\0\3\10\10\0\1\10\1\53"+
    "\11\10\1\54\24\10\14\0\2\10\1\0\3\10\10\0"+
    "\10\10\1\55\10\10\1\56\16\10\14\0\2\10\1\0"+
    "\3\10\10\0\5\10\1\57\32\10\14\0\2\10\1\0"+
    "\3\10\10\0\11\10\1\60\26\10\14\0\2\10\1\0"+
    "\3\10\10\0\10\10\1\61\27\10\14\0\2\10\1\0"+
    "\3\10\10\0\1\10\1\62\14\10\1\63\21\10\14\0"+
    "\2\10\1\0\3\10\10\0\20\10\1\64\17\10\14\0"+
    "\2\10\1\0\3\10\10\0\11\10\1\65\26\10\14\0"+
    "\2\10\1\0\3\10\10\0\32\10\1\66\5\10\14\0"+
    "\2\10\1\0\3\10\10\0\27\10\1\67\10\10\14\0"+
    "\2\10\1\0\3\10\64\0\1\70\2\0\1\70\55\0"+
    "\1\4\72\0\1\4\74\0\1\4\73\0\1\4\73\0"+
    "\1\4\63\0\1\71\6\0\1\35\2\0\1\35\5\0"+
    "\3\72\1\0\64\72\1\0\1\72\26\0\1\73\23\0"+
    "\1\71\6\0\1\35\2\0\1\35\1\73\4\0\3\41"+
    "\1\74\64\41\1\74\1\41\2\75\1\76\67\75\5\0"+
    "\2\10\1\77\35\10\14\0\2\10\1\0\3\10\10\0"+
    "\5\10\1\100\32\10\14\0\2\10\1\0\3\10\10\0"+
    "\23\10\1\101\14\10\14\0\2\10\1\0\3\10\10\0"+
    "\6\10\1\102\31\10\14\0\2\10\1\0\3\10\10\0"+
    "\10\10\1\103\27\10\14\0\2\10\1\0\3\10\10\0"+
    "\6\10\1\104\31\10\14\0\2\10\1\0\3\10\10\0"+
    "\2\10\1\105\35\10\14\0\2\10\1\0\3\10\10\0"+
    "\1\10\1\103\36\10\14\0\2\10\1\0\3\10\10\0"+
    "\11\10\1\106\26\10\14\0\2\10\1\0\3\10\10\0"+
    "\12\10\1\107\25\10\14\0\2\10\1\0\3\10\10\0"+
    "\5\10\1\110\32\10\14\0\2\10\1\0\3\10\10\0"+
    "\13\10\1\111\24\10\14\0\2\10\1\0\3\10\10\0"+
    "\5\10\1\112\32\10\14\0\2\10\1\0\3\10\10\0"+
    "\16\10\1\113\21\10\14\0\2\10\1\0\3\10\10\0"+
    "\13\10\1\45\24\10\14\0\2\10\1\0\3\10\10\0"+
    "\10\10\1\114\27\10\14\0\2\10\1\0\3\10\10\0"+
    "\2\10\1\115\35\10\14\0\2\10\1\0\3\10\10\0"+
    "\24\10\1\116\13\10\14\0\2\10\1\0\3\10\10\0"+
    "\33\10\1\117\4\10\14\0\2\10\1\0\3\10\10\0"+
    "\36\10\1\120\1\10\14\0\2\10\1\0\3\10\55\0"+
    "\1\71\6\0\1\70\2\0\1\70\23\0\1\121\22\0"+
    "\1\121\17\0\1\71\2\0\1\71\5\0\3\72\1\0"+
    "\57\72\1\122\4\72\1\0\1\72\10\0\1\123\3\0"+
    "\1\123\1\0\1\123\3\0\3\123\7\0\1\123\4\0"+
    "\2\123\16\0\1\123\2\0\1\123\1\0\1\123\3\0"+
    "\2\75\1\124\67\75\1\0\1\125\1\76\74\0\3\10"+
    "\1\45\34\10\14\0\2\10\1\0\3\10\10\0\11\10"+
    "\1\126\26\10\14\0\2\10\1\0\3\10\10\0\10\10"+
    "\1\127\27\10\14\0\2\10\1\0\3\10\10\0\7\10"+
    "\1\115\30\10\14\0\2\10\1\0\3\10\10\0\10\10"+
    "\1\45\27\10\14\0\2\10\1\0\3\10\10\0\11\10"+
    "\1\130\26\10\14\0\2\10\1\0\3\10\10\0\12\10"+
    "\1\45\25\10\14\0\2\10\1\0\3\10\10\0\16\10"+
    "\1\131\21\10\14\0\2\10\1\0\3\10\10\0\11\10"+
    "\1\45\26\10\14\0\2\10\1\0\3\10\10\0\11\10"+
    "\1\132\26\10\14\0\2\10\1\0\3\10\10\0\2\10"+
    "\1\133\35\10\14\0\2\10\1\0\3\10\10\0\6\10"+
    "\1\134\31\10\14\0\2\10\1\0\3\10\10\0\12\10"+
    "\1\105\25\10\14\0\2\10\1\0\3\10\10\0\12\10"+
    "\1\104\25\10\14\0\2\10\1\0\3\10\10\0\10\10"+
    "\1\107\27\10\14\0\2\10\1\0\3\10\10\0\27\10"+
    "\1\135\10\10\14\0\2\10\1\0\3\10\10\0\34\10"+
    "\1\130\3\10\14\0\2\10\1\0\3\10\10\0\37\10"+
    "\1\117\14\0\2\10\1\0\3\10\50\0\1\136\13\0"+
    "\1\137\2\0\1\137\5\0\1\140\1\125\1\124\67\140"+
    "\5\0\13\10\1\141\24\10\14\0\2\10\1\0\3\10"+
    "\10\0\11\10\1\142\26\10\14\0\2\10\1\0\3\10"+
    "\10\0\25\10\1\45\12\10\14\0\2\10\1\0\3\10"+
    "\10\0\4\10\1\143\33\10\14\0\2\10\1\0\3\10"+
    "\10\0\4\10\1\144\33\10\14\0\2\10\1\0\3\10"+
    "\10\0\13\10\1\145\24\10\14\0\2\10\1\0\3\10"+
    "\10\0\13\10\1\146\24\10\14\0\2\10\1\0\3\10"+
    "\64\0\1\137\2\0\1\137\5\0\2\140\1\124\67\140"+
    "\5\0\17\10\1\147\20\10\14\0\2\10\1\0\3\10"+
    "\10\0\22\10\1\150\15\10\14\0\2\10\1\0\3\10"+
    "\10\0\3\10\1\105\34\10\14\0\2\10\1\0\3\10"+
    "\10\0\14\10\1\45\23\10\14\0\2\10\1\0\3\10"+
    "\10\0\4\10\1\45\33\10\14\0\2\10\1\0\3\10"+
    "\10\0\13\10\1\151\24\10\14\0\2\10\1\0\3\10"+
    "\10\0\16\10\1\152\21\10\14\0\2\10\1\0\3\10"+
    "\10\0\11\10\1\153\26\10\14\0\2\10\1\0\3\10"+
    "\10\0\16\10\1\154\21\10\14\0\2\10\1\0\3\10"+
    "\10\0\15\10\1\107\22\10\14\0\2\10\1\0\3\10"+
    "\10\0\4\10\1\155\33\10\14\0\2\10\1\0\3\10"+
    "\10\0\30\10\1\45\7\10\14\0\2\10\1\0\3\10"+
    "\10\0\5\10\1\105\32\10\14\0\2\10\1\0\3\10"+
    "\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5800];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\35\1\1\0\25\1\1\0"+
    "\1\1\2\0\1\11\1\1\1\0\22\1\1\0\2\1"+
    "\1\0\1\11\10\1\1\0\1\1\1\0\15\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public String lexeme;
    public int line;
    public int column;
    public int length;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 230) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public String yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { lexeme = yytext(); line = (yyline + 1); column = (yycolumn + 1); length = yylength(); return "Lexical error:";
            }
          case 15: break;
          case 2: 
            { return "OPERATOR OR PUNTATION MARK: " + yytext() + " in line: " + (yyline + 1) + " columns: " + (yycolumn + 1) + " - " + ((yycolumn + 1) + yylength() - 1);
            }
          case 16: break;
          case 3: 
            { /*se ignoran los espacios y tabuladores*/
            }
          case 17: break;
          case 4: 
            { if(yylength() > 31)
                                                                    {
                                                                        String aux = yytext().substring(0,31);
                                                                        
                                                                        return "IDENTIFIER: " + aux + " in line: " + (yyline + 1) + " columns: " + (yycolumn + 1) + " - " + ((yycolumn + 1) + yylength() - 1) + " exceeded the max limit length. Identifier truncated.";                                                                       
                                                                    }
                                                                    else 
                                                                    {
                                                                        return "IDENTIFIER: " + yytext() + " in line: " + (yyline + 1) + " columns: " + (yycolumn + 1) + " - " + ((yycolumn + 1) + yylength() - 1); 
                                                                    }
            }
          case 18: break;
          case 5: 
            { return "INTEGER: " + yytext() + " in line: " + (yyline + 1) + " columns: " + (yycolumn + 1) + " - " + ((yycolumn + 1) + yylength() - 1);
            }
          case 19: break;
          case 6: 
            { /*lleva la cuenta de lineas*/
            }
          case 20: break;
          case 7: 
            { /*se ignoran los comentarios de linea*/
            }
          case 21: break;
          case 8: 
            { return "RESERVED WORD: " + yytext() + " in line: " + (yyline + 1) + " columns: " + (yycolumn + 1) + " - " + ((yycolumn + 1) + yylength() - 1);
            }
          case 22: break;
          case 9: 
            { return "DOUBLE: " + yytext() + " in line: " + (yyline + 1) + " columns: " + (yycolumn + 1) + " - " + ((yycolumn + 1) + yylength() - 1);
            }
          case 23: break;
          case 10: 
            { return "Unfinished comment " + yytext() + " found in line: " + (yyline + 1) + " columns: " + (yycolumn + 1) + " - " + ((yycolumn + 1) + yylength() - 1);
            }
          case 24: break;
          case 11: 
            { return "STRING: " + yytext() + " in line: " + (yyline + 1) + " columns: " + (yycolumn + 1) + " - " + ((yycolumn + 1) + yylength() - 1);
            }
          case 25: break;
          case 12: 
            { return "INTEGER HEXADECIMAL: " + yytext() + " in line: " + yyline + " columns: " + (yycolumn + 1) + " - " + ((yycolumn + 1) + yylength() - 1);
            }
          case 26: break;
          case 13: 
            { /*se ignoran los comentarios de bloque*/
            }
          case 27: break;
          case 14: 
            { return "BOOLEAN: " + yytext() + " in line: " + (yyline + 1) + " columns: " + (yycolumn + 1) + " - " + ((yycolumn + 1) + yylength() - 1);
            }
          case 28: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
